### ISSUE TITLE
ERROR: No suitable staging package found | do_populate_sysroot_setscene

### ISSUE THREAD

**Issue by GuillaumeLamottedIncamps** [FredKellerman/Microzed-PYNQ#7]
Hello, I'm trying to build a SD card for a Microzed, but it doesn't work . 

I did execute the setup_host.sh from the 2.6 branch from the xilinx github, and I have installed Vitis and Petalinux in 2020.1 version (and I used "source" before executing buildfast.sh).

However, my build fails. It succeeds building the default overlay, but when it comes to build the PYNQ SD Image, it doesn't. 
The failure is due to an incapacity to find a sstate file : 

NOTE: Sstate package /home/guillaume/Documents/Microzed-PYNQ-master/PYNQ-git/sdbuild/build/microzed-7020/petalinux_project/build/sstate-cache/universal/6a/e3/sstate:python3-setuptools-native:x86_64-linux:41.2.0:r0:x86_64:3:6ae3c70d422fd7132a2f013fe7a53f7a6da3303d96b54a0fb14ef662d446333d_populate_sysroot.tgz does not exist
ERROR: No suitable staging package found
DEBUG: Python function do_populate_sysroot_setscene finished

In the report log file, it can be seen that the script try to access to the .tgz file through internet, but an error 403 occurs : 

Connecting to petalinux.xilinx.com|23.51.72.230|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-04-21 12:46:44 ERROR 403: Forbidden.

And that for the .tgz.file it does the smae thing, but it works : 

Connecting to petalinux.xilinx.com|23.51.72.230|:80... connected.
HTTP request sent, awaiting response... 200 OK

But what is strangiest, is that when I'm looking, after this failed build, in the repository /home/guillaume/Documents/Microzed-PYNQ-master/PYNQ-git/sdbuild/build/microzed-7020/petalinux_project/build/sstate-cache/universal , I find the 2 files required (the .tgz and .tgz.siginfo).

I have also try to download those files before executing buildfast.sh , but I haven't find a repository nor a path that would help the sccript to find those.

Do you have any ideas how to resolve this problem ?

Thanks,
Guillaume.

**Comment by FredKellerman** [comment]
Hi Guillaume,  I have build these myself more than a few times and no issues for me but let's dig a little deeper.

First, can you try the buildfast.sh I've attached here?  I've modified it to make sure wget validates the files that are downloaded.

If the issue still exists after ensuring the integrity of the downloaded files.  Can you try to build the bsp by itself?  The bsp can be found from where buildfast.sh puts it, you can also find the bsp in the Release section of this github: https://github.com/FredKellerman/Microzed-PYNQ/releases/download/v2.6.0/microzed.bsp

Once you have the bsp file you can extract it's contents using tar -xvf ./microzed.bsp

'cd' into the new dir, make sure you source settings.sh for PetaLinux 2020.1 and then you should be able to just enter and execute petalinux-build.  Let me know if that has the same issue.

Kind regards,
-Fred

[buildfast.zip](https://github.com/FredKellerman/Microzed-PYNQ/files/11297155/buildfast.zip)

**Comment by GuillaumeLamottedIncamps** [comment]
Hi Fred,

Somehow the building work 2h after my mail !

I think that my issue was in part due to my firewall who didn't like
downloading files from xilinx without analysing them. I retried to do the
building at 17:20 and it worked without the error that I have mentionned, I
guess that the firewall whitelisted xilinx after a few analysis, and
without this control, the building was free to complete.

However in order to understand what's going on during the building, I will
try your advices next monday.

Thanks for your reactivity,
Have a great week-end.

Guillaume

Le ven. 21 avr. 2023 à 17:27, Fred Kellerman ***@***.***> a
écrit :

**Comment by FredKellerman** [comment]
:-)  That is good news!  PetaLinux fetches a lot of files from the internet and sometimes the servers can't keep up.  There is a way to setup to pre-download the sstate files but it has its own downsides.

No need to try anything if you are up and running, you probably have more important work to do since you are customizing the image.

I cannot promise a fast turn around but we could update this to v3.0.1 PYNQ if needed.  If there are additional features you would like to see, don't hesitate to reach out.

-Fred

**Comment by FredKellerman** [comment]
Hi Guillaume,

I replied and closed the github issue.

Do let me know if you cannot get it to build.  I can probably upload an SD
image to the releases tab just for you and then take it down.  I don't have
a lot of extra time and I'm not able to support a pre-built SD image for
the world.

Also keep in mind the Ethernet MAC is random each power cycle, this may
cause your DHCP server to issue a different IP address each time.  I may
have a fix for that and try it out someday, basically it needs a bsp change
in uboot to have the MAC address read from the eeprom.

Kind regards,
-Fred

**Comment by GuillaumeLamottedIncamps** [comment]
Hi Fred,

Since my last email I succeeded to build the image for an SD card, and I
have been exploring the capacities of PYNQ with the microzed.

Now I'm trying to boot PYNQ from the QSPI Flash memory (booting from the SD
Card is fine for testing but not for the expected utilisation), but I can't
find any solution that is working. Indeed I have seen that Avnet has
published a document explaining how to boot a new image of a linux kernel
(that you will find in the attachments), however I fail to generate the
.mcs file.

I have understood that the image of the linux kernel is in the "image.ub"
file generated by your script, and that it is not the only component of
this file (there is also the Flattened Device Tree Blob and the
configuration). I have try to extract those components with mkimage or dd
(OS : Ubuntu 18.0, the one that generated the PYNQ build) but I get the
feeling that it is not working.

Have you ever tried to boot PYNQ without the SD card ? Do you already know
the solution to my problem ?

Have a great day,
Guillaume

Le ven. 21 avr. 2023 à 20:34, Fred Kellerman ***@***.***> a
écrit :

> Hi Guillaume,
>
> I replied and closed the github issue.
>
> Do let me know if you cannot get it to build. I can probably upload an SD
> image to the releases tab just for you and then take it down. I don't have
> a lot of extra time and I'm not able to support a pre-built SD image for
> the world.
>
> Also keep in mind the Ethernet MAC is random each power cycle, this may
> cause your DHCP server to issue a different IP address each time. I may
> have a fix for that and try it out someday, basically it needs a bsp change
> in uboot to have the MAC address read from the eeprom.
>
> Kind regards,
> -Fred
>
>
> On Fri, Apr 21, 2023 at 1:03 PM GuillaumeLamottedIncamps <

**Comment by FredKellerman** [comment]
Hi Guillaume,

I have never attempted this as many, perhaps most ZYNQ boards do not have
enough QSPI or flash memory to accommodate PYNQ with the Ubuntu rootfs.
The older images were about 7GB and the latest 3.0.1 is around 9GB now.  Do
keep in mind that 16GB minimum is recommended for PYNQ.  The QSPI on the
Microzed is not that large.

In theory you could host fsbl, u-boot and maybe the kernel on the QSPI and
use the SD card for the rootfs.  Basically you would move what is on the
fat32 partition of the PYNQ SD card to QSPI.  But this is not
straightforward, you also need to change the linker map settings and boot
code to be correct for starting up on the QSPI as well.  To do the latter
you could study the AMD pynq makefile that builds it all and either
override that or manually do it post build.

Kind regards,
-Fred

**Comment by GuillaumeLamottedIncamps** [comment]
Hi Fred,

Thanks for you answer, it opened my eyes on the subject (I'm discovering
customed Linux while working on them).

I have understood that if I want to boot PYNQ without the micro SD card, I
will need to add some eMMC to my system in order to host the /dev/root
which weights 6.2GB (which indeed won't fit in the QSPI memory).
It's quite a challenge for me as I am still a student, but I will try my
best.

I will let you know if it works out.

Have a good day,
Guillaume

Le mar. 6 juin 2023 à 20:08, Fred Kellerman ***@***.***> a
écrit :

> Hi Guillaume,
>
> I have never attempted this as many, perhaps most ZYNQ boards do not have
> enough QSPI or flash memory to accommodate PYNQ with the Ubuntu rootfs.
> The older images were about 7GB and the latest 3.0.1 is around 9GB now. Do
> keep in mind that 16GB minimum is recommended for PYNQ. The QSPI on the
> Microzed is not that large.
>
> In theory you could host fsbl, u-boot and maybe the kernel on the QSPI and
> use the SD card for the rootfs. Basically you would move what is on the
> fat32 partition of the PYNQ SD card to QSPI. But this is not
> straightforward, you also need to change the linker map settings and boot
> code to be correct for starting up on the QSPI as well. To do the latter
> you could study the AMD pynq makefile that builds it all and either
> override that or manually do it post build.
>
> Kind regards,
> -Fred
>
> On Tue, Jun 6, 2023 at 9:18 AM GuillaumeLamottedIncamps <
